---
title: "Flickr Example1"
author: "Yi Lin Liu"
date: "April 6, 2017"
output: 
    html_document:
    toc: true
    toc.depth: 6
---

*****

##  Goal:
__To use the public search to search for photos and try
    to extract the meta data as well as the location data
    and save to a file.__
    
    

```{r FlickrEx1 SetUP,message=F,error=F,warning=F}

    rm(list = ls())
    library(httr)
    library(jsonlite)
    library(xml2)
    library(rvest)

    token <- readRDS("./token.R")
    app_Key <- "08adb0273ae63e5c07c249f5a621e7cb"
    app_Secret <- "89e0a70bfb48e7f4"
    
```


*****

##  1:  Searching for public photos:

*   [Photo search](https://www.flickr.com/services/api/flickr.photos.search.html)

*   [PlaceId search](https://www.flickr.com/services/api/flickr.places.find.html)

```{r FlickrEx1 PhotoSearch}

    endpoint <- "https://api.flickr.com/services/rest"
    arguments <- c(method="flickr.photos.search",
                   api_key=app_Key,
                   tags = "river,mountain", placeid ="", 
                  has_geo=1,
                  per_page=10)
    
    ##Finding the placeid for Canada:
    place_args<- c(method="flickr.places.find",
                 api_key = app_Key, 
                 query="Canada")
    place_Id_Request <- paste(endpoint,
        paste(names(place_args), place_args,sep="=",collapse="&"),
        sep="?")
    
    raw_Place <- GET(place_Id_Request)
    
    ##  Validation of requests will be ignored for now.
    
    ##  Just going to take the ID of the first one, 
    ##  manually verified to be canada. For more accurate,
    ##  use lat and lng to search for place id
    place_id <- xml2::read_xml(raw_Place$content) %>%
        xml_node("places place") %>%
        xml_attr("place_id")
    
    
    ## adding the place id back into arguments
    arguments["placeid"]=place_id
    
    
    
    ##searching
    
    search_Req <- paste(endpoint, 
        paste(names(arguments),arguments,sep="=",collapse="&"),
        sep="?")
    search_Raw <- GET(search_Req)
    ids <- xml2::read_xml(search_Raw$content) %>%
            xml_nodes("photos photo") %>%
            xml_attr("id")
    secrets <-xml2::read_xml(search_Raw$content) %>%
            xml_nodes("photos photo") %>%
            xml_attr("secret")

```

*****

##  2:  Getting all Metadata:

*   Saved under `meta.txt`.

```{r FlickrEX1 metadata}
    ##  Looping through to extract the metadata
    ##  Sometimes, the permission is not granted.
    ##  It is still recorded

    for(i in 1:length(ids)){
        meta_Args <- c(method="flickr.photos.getExif",
                   api_key=app_Key,
                   photo_id=ids[i],
                   secret=secrets[i])
        
        ##  Making request
        meta_Req <- paste(endpoint, 
        paste(names(meta_Args),meta_Args,sep="=",collapse="&"),
        sep="?")
        
        metadata = GET(meta_Req)
        metadata = rawToChar(metadata$content)
        
        ##  Saving returned XML to a file
        write.table(metadata,file="meta.txt",append=T,
                    sep="\n\n",col.names=F,row.names=F)
    }
    
```

*****

##  3:  Getting Location Data:

*   Saved under `location.txt`.

```{r FlickrEx2 location}

for(i in 1:length(ids)){
        args <- c(method="flickr.photos.geo.getLocation",
                   api_key=app_Key,
                   photo_id=ids[i])
        
        ##  Making request
        req <- paste(endpoint, 
        paste(names(args),args,sep="=",collapse="&"),
        sep="?")
        
        data = GET(req)
        data = rawToChar(data$content)
        
        ##  Saving returned XML to a file
        write.table(data,file="location.txt",append=T,
                    sep="\n\n",col.names=F,row.names=F)
    }
```