---
title: "Google Maps Mini-Project"
author: "paul"
date: "March 22, 2017"
output: 
    html_document:
    toc: true
    toc.depth: 5
---


### Setting up List of Cities

*   [List of cities](http://www.canada-city.ca/all-cities-in-canada.php) copied into a excel sheet,
    needs reformating to extract __city name__ and __province__.

```{r Setting up List of Cities For Extraction}
    ## Sample city format: 1: 100 Mile House, British Columbia 

    raw_Citys = read.table("List of Cities.txt",header = TRUE, sep ="\n")

    ## getting rid of numbers:
    
    raw_Citys = lapply(raw_Citys, function(x){
        gsub(pattern = "[0-9]+:", "",x)
    })
    
    raw_Citys = unlist(raw_Citys)
    
    
    ## Seperating into city and province
    citys = list()
    province = list()
    for(i in 1: length(raw_Citys)){
        seperated = unlist( strsplit(raw_Citys[[i]],",") )
        citys[[i]] = gsub(" ","",seperated[1])
        province[[i]] = gsub(" ","",seperated[2])
        
    }
    
    raw_Citys_DF = data.frame(city=unlist(citys),
                    province=unlist(province))

    rm(list = setdiff(ls(),c("raw_Citys_DF")))
```



### Getting the orgin and destination cities randomly:

*   Randomly select origin and destination pairs

```{r orgin and destination}
    library(dplyr)


    ab_Citys = dplyr::filter(raw_Citys_DF, province=="Alberta")
    
    ## Selecting origin and dest citys
    origin_Citys = dplyr::sample_n(ab_Citys,100)
    dest_Citys = dplyr::sample_n(dplyr::filter(raw_Citys_DF,province != "Alberta"), 
                                 size=100)
    
    ## renaming variables 
    colnames(origin_Citys) = c("orig_city", "orig_province")
    colnames(dest_Citys) = c("dest_city","dest_province")
    
    ## formatting to out_DF and clearing memory
    out_DF = cbind(origin_Citys,dest_Citys)
    
    rm(list = setdiff(ls(),c("out_DF")))
    
    
    ## write the current out_DF to a file 
    ## to remove the random elements 
    # 
    # if(!file.exists("progress.txt")){
    #     file.create("progress.txt")
    # }
    # 
     # write.table(out_DF, file="progress.txt",sep=",",row.names=FALSE)

```



### Getting Direction information


```{r google credentials}
    api_Key = "AIzaSyBGTs-gZCbyP8n0Hvw_VZ76Z6YrST1DNa8"
    host = "https://maps.googleapis.com/maps/api"

```


https://maps.googleapis.com/maps/api/geocode/json?address=1600+Amphitheatre+Parkway,+Mountain+View,+CA&key=YOUR_API_KEY

```{r function for lat and lng}

## takes lists containing: (orig_City, orig_Province,
##  dest_city,dest_provice) and a api_Key
##  assume that the lists are matching and same length

## return a data frame containing lat,lng, route information

    lat_Lng = function(orig_city,orig_province,
                       dest_city,dest_province,
                        api_Key){
        
        ##libraries needed
        require(jsonlite)
        require(httr)
        
        
        ## some google request information
        host = "https://maps.googleapis.com/maps/api"
        service = "/directions/json"
        
        
        ## lists to fill for a data frame
        orig_lat = list()
        orig_lng = list()
        dest_lat = list()
        dest_lng = list()
        polyline = list()
        time_text = list()
        time_value = list()
        distance_text = list()
        distance_value = list()
        
        ##looping through list
        for( i in length(orig_city)){
            
            ## Getting names of city and province
            origin = paste(orig_city[[i]],orig_province[[i]],sep=",")
            origin = gsub(" ", "+",origin)
            dest = paste(dest_city[[i]],dest_province[[i]],sep=",")
            dest = gsub(" ", "+", dest)
            
            ##formatting api request:
            directions_Request = paste(host, service,"?origin=",origin,
                               "&destination=",dest,
                               "&key=",api_Key,sep ="")
            
            ## getting nested response list
            raw = GET(directions_Request)
            
            directions_Response = jsonlite::fromJSON(
                content(raw,"text")
            )
            
            if(directions_Response$status != "ok")
                warnings("Request not successful")
            
            route_info = directions_Response$routes$legs[[1]]
            
            ##geting lat and lng for origin and destination
            start_df = route_info[["start_location"]]
            ## a bit truncated
            orig_lat[[i]] = start_df$lat
            orig_lng[[i]] = start_df$lng
            end_df = route_info[["end_location"]]
            dest_lat[[i]] = end_df$lat
            dest_lng[[i]]= end_df$lng
            
            
            ##getting time, distance info
            time_value[[i]] = route_info$duration$value
            time_text[[i]] = route_info$duration$text
            distance_text[[i]] = route_info$distance$text
            distance_value[[i]] = route_info$distance$value
            
        }
        return(distance_text)
        
    }    
```



```{r testing functions}

    progress_DF = read.table("progress.txt", header=TRUE,sep=",")

    test= lat_Lng(list(progress_DF$orig_city[[1]]), 
                  list(progress_DF$orig_province[[1]]),
                  list(progress_DF$dest_city[[1]]),
                  list(progress_DF$dest_province[[1]]),api_Key = api_Key)
1
```